package com.app.market.dao.mapper.mms.mybatis;

import com.app.market.dao.entity.mms.mybatis.MmsInfo;
import com.app.market.dao.entity.mms.mybatis.MmsInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MmsInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mms_info
     *
     * @mbggenerated Fri Mar 10 13:36:42 CST 2017
     */
    int countByExample(MmsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mms_info
     *
     * @mbggenerated Fri Mar 10 13:36:42 CST 2017
     */
    int deleteByExample(MmsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mms_info
     *
     * @mbggenerated Fri Mar 10 13:36:42 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mms_info
     *
     * @mbggenerated Fri Mar 10 13:36:42 CST 2017
     */
    int insert(MmsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mms_info
     *
     * @mbggenerated Fri Mar 10 13:36:42 CST 2017
     */
    int insertSelective(MmsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mms_info
     *
     * @mbggenerated Fri Mar 10 13:36:42 CST 2017
     */
    List<MmsInfo> selectByExample(MmsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mms_info
     *
     * @mbggenerated Fri Mar 10 13:36:42 CST 2017
     */
    MmsInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mms_info
     *
     * @mbggenerated Fri Mar 10 13:36:42 CST 2017
     */
    int updateByExampleSelective(@Param("record") MmsInfo record, @Param("example") MmsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mms_info
     *
     * @mbggenerated Fri Mar 10 13:36:42 CST 2017
     */
    int updateByExample(@Param("record") MmsInfo record, @Param("example") MmsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mms_info
     *
     * @mbggenerated Fri Mar 10 13:36:42 CST 2017
     */
    int updateByPrimaryKeySelective(MmsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mms_info
     *
     * @mbggenerated Fri Mar 10 13:36:42 CST 2017
     */
    int updateByPrimaryKey(MmsInfo record);
}