package com.app.market.dao.mapper.mms.mybatis;

import com.app.market.dao.entity.mms.mybatis.MmsPointsChange;
import com.app.market.dao.entity.mms.mybatis.MmsPointsChangeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MmsPointsChangeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mms_points_change
     *
     * @mbggenerated Fri Mar 10 15:49:52 CST 2017
     */
    int countByExample(MmsPointsChangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mms_points_change
     *
     * @mbggenerated Fri Mar 10 15:49:52 CST 2017
     */
    int deleteByExample(MmsPointsChangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mms_points_change
     *
     * @mbggenerated Fri Mar 10 15:49:52 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mms_points_change
     *
     * @mbggenerated Fri Mar 10 15:49:52 CST 2017
     */
    int insert(MmsPointsChange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mms_points_change
     *
     * @mbggenerated Fri Mar 10 15:49:52 CST 2017
     */
    int insertSelective(MmsPointsChange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mms_points_change
     *
     * @mbggenerated Fri Mar 10 15:49:52 CST 2017
     */
    List<MmsPointsChange> selectByExample(MmsPointsChangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mms_points_change
     *
     * @mbggenerated Fri Mar 10 15:49:52 CST 2017
     */
    MmsPointsChange selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mms_points_change
     *
     * @mbggenerated Fri Mar 10 15:49:52 CST 2017
     */
    int updateByExampleSelective(@Param("record") MmsPointsChange record, @Param("example") MmsPointsChangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mms_points_change
     *
     * @mbggenerated Fri Mar 10 15:49:52 CST 2017
     */
    int updateByExample(@Param("record") MmsPointsChange record, @Param("example") MmsPointsChangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mms_points_change
     *
     * @mbggenerated Fri Mar 10 15:49:52 CST 2017
     */
    int updateByPrimaryKeySelective(MmsPointsChange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mms_points_change
     *
     * @mbggenerated Fri Mar 10 15:49:52 CST 2017
     */
    int updateByPrimaryKey(MmsPointsChange record);
}