package com.app.market.dao.mapper.mms.mybatis;

import com.app.market.dao.entity.mms.mybatis.MmsPointsChangeDetail;
import com.app.market.dao.entity.mms.mybatis.MmsPointsChangeDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MmsPointsChangeDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mms_points_change_detail
     *
     * @mbggenerated Fri Mar 10 16:25:50 CST 2017
     */
    int countByExample(MmsPointsChangeDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mms_points_change_detail
     *
     * @mbggenerated Fri Mar 10 16:25:50 CST 2017
     */
    int deleteByExample(MmsPointsChangeDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mms_points_change_detail
     *
     * @mbggenerated Fri Mar 10 16:25:50 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mms_points_change_detail
     *
     * @mbggenerated Fri Mar 10 16:25:50 CST 2017
     */
    int insert(MmsPointsChangeDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mms_points_change_detail
     *
     * @mbggenerated Fri Mar 10 16:25:50 CST 2017
     */
    int insertSelective(MmsPointsChangeDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mms_points_change_detail
     *
     * @mbggenerated Fri Mar 10 16:25:50 CST 2017
     */
    List<MmsPointsChangeDetail> selectByExample(MmsPointsChangeDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mms_points_change_detail
     *
     * @mbggenerated Fri Mar 10 16:25:50 CST 2017
     */
    MmsPointsChangeDetail selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mms_points_change_detail
     *
     * @mbggenerated Fri Mar 10 16:25:50 CST 2017
     */
    int updateByExampleSelective(@Param("record") MmsPointsChangeDetail record, @Param("example") MmsPointsChangeDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mms_points_change_detail
     *
     * @mbggenerated Fri Mar 10 16:25:50 CST 2017
     */
    int updateByExample(@Param("record") MmsPointsChangeDetail record, @Param("example") MmsPointsChangeDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mms_points_change_detail
     *
     * @mbggenerated Fri Mar 10 16:25:50 CST 2017
     */
    int updateByPrimaryKeySelective(MmsPointsChangeDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mms_points_change_detail
     *
     * @mbggenerated Fri Mar 10 16:25:50 CST 2017
     */
    int updateByPrimaryKey(MmsPointsChangeDetail record);
}