package com.app.market.dao.entity.crm.mybatis;

public class CrmSupInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_sup_info.id
     *
     * @mbggenerated Wed Mar 01 15:35:41 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_sup_info.name
     *
     * @mbggenerated Wed Mar 01 15:35:41 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_sup_info.address
     *
     * @mbggenerated Wed Mar 01 15:35:41 CST 2017
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_sup_info.contact
     *
     * @mbggenerated Wed Mar 01 15:35:41 CST 2017
     */
    private String contact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_sup_info.remark
     *
     * @mbggenerated Wed Mar 01 15:35:41 CST 2017
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_sup_info.mobile
     *
     * @mbggenerated Wed Mar 01 15:35:41 CST 2017
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_sup_info.org_id
     *
     * @mbggenerated Wed Mar 01 15:35:41 CST 2017
     */
    private String orgId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_sup_info.id
     *
     * @return the value of crm_sup_info.id
     *
     * @mbggenerated Wed Mar 01 15:35:41 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_sup_info.id
     *
     * @param id the value for crm_sup_info.id
     *
     * @mbggenerated Wed Mar 01 15:35:41 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_sup_info.name
     *
     * @return the value of crm_sup_info.name
     *
     * @mbggenerated Wed Mar 01 15:35:41 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_sup_info.name
     *
     * @param name the value for crm_sup_info.name
     *
     * @mbggenerated Wed Mar 01 15:35:41 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_sup_info.address
     *
     * @return the value of crm_sup_info.address
     *
     * @mbggenerated Wed Mar 01 15:35:41 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_sup_info.address
     *
     * @param address the value for crm_sup_info.address
     *
     * @mbggenerated Wed Mar 01 15:35:41 CST 2017
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_sup_info.contact
     *
     * @return the value of crm_sup_info.contact
     *
     * @mbggenerated Wed Mar 01 15:35:41 CST 2017
     */
    public String getContact() {
        return contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_sup_info.contact
     *
     * @param contact the value for crm_sup_info.contact
     *
     * @mbggenerated Wed Mar 01 15:35:41 CST 2017
     */
    public void setContact(String contact) {
        this.contact = contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_sup_info.remark
     *
     * @return the value of crm_sup_info.remark
     *
     * @mbggenerated Wed Mar 01 15:35:41 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_sup_info.remark
     *
     * @param remark the value for crm_sup_info.remark
     *
     * @mbggenerated Wed Mar 01 15:35:41 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_sup_info.mobile
     *
     * @return the value of crm_sup_info.mobile
     *
     * @mbggenerated Wed Mar 01 15:35:41 CST 2017
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_sup_info.mobile
     *
     * @param mobile the value for crm_sup_info.mobile
     *
     * @mbggenerated Wed Mar 01 15:35:41 CST 2017
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_sup_info.org_id
     *
     * @return the value of crm_sup_info.org_id
     *
     * @mbggenerated Wed Mar 01 15:35:41 CST 2017
     */
    public String getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_sup_info.org_id
     *
     * @param orgId the value for crm_sup_info.org_id
     *
     * @mbggenerated Wed Mar 01 15:35:41 CST 2017
     */
    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }
}