package com.app.market.dao.mapper.im.mybatis;

import com.app.market.dao.entity.im.mybatis.ImProductChange;
import com.app.market.dao.entity.im.mybatis.ImProductChangeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ImProductChangeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_product_change
     *
     * @mbggenerated Wed Mar 01 18:16:49 CST 2017
     */
    int countByExample(ImProductChangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_product_change
     *
     * @mbggenerated Wed Mar 01 18:16:49 CST 2017
     */
    int deleteByExample(ImProductChangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_product_change
     *
     * @mbggenerated Wed Mar 01 18:16:49 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_product_change
     *
     * @mbggenerated Wed Mar 01 18:16:49 CST 2017
     */
    int insert(ImProductChange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_product_change
     *
     * @mbggenerated Wed Mar 01 18:16:49 CST 2017
     */
    int insertSelective(ImProductChange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_product_change
     *
     * @mbggenerated Wed Mar 01 18:16:49 CST 2017
     */
    List<ImProductChange> selectByExample(ImProductChangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_product_change
     *
     * @mbggenerated Wed Mar 01 18:16:49 CST 2017
     */
    ImProductChange selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_product_change
     *
     * @mbggenerated Wed Mar 01 18:16:49 CST 2017
     */
    int updateByExampleSelective(@Param("record") ImProductChange record, @Param("example") ImProductChangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_product_change
     *
     * @mbggenerated Wed Mar 01 18:16:49 CST 2017
     */
    int updateByExample(@Param("record") ImProductChange record, @Param("example") ImProductChangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_product_change
     *
     * @mbggenerated Wed Mar 01 18:16:49 CST 2017
     */
    int updateByPrimaryKeySelective(ImProductChange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_product_change
     *
     * @mbggenerated Wed Mar 01 18:16:49 CST 2017
     */
    int updateByPrimaryKey(ImProductChange record);
}