package com.app.market.dao.mapper.im.mybatis;

import com.app.market.dao.entity.im.mybatis.ImProductChangeDetail;
import com.app.market.dao.entity.im.mybatis.ImProductChangeDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ImProductChangeDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_product_change_detail
     *
     * @mbggenerated Wed Mar 01 18:17:01 CST 2017
     */
    int countByExample(ImProductChangeDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_product_change_detail
     *
     * @mbggenerated Wed Mar 01 18:17:01 CST 2017
     */
    int deleteByExample(ImProductChangeDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_product_change_detail
     *
     * @mbggenerated Wed Mar 01 18:17:01 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_product_change_detail
     *
     * @mbggenerated Wed Mar 01 18:17:01 CST 2017
     */
    int insert(ImProductChangeDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_product_change_detail
     *
     * @mbggenerated Wed Mar 01 18:17:01 CST 2017
     */
    int insertSelective(ImProductChangeDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_product_change_detail
     *
     * @mbggenerated Wed Mar 01 18:17:01 CST 2017
     */
    List<ImProductChangeDetail> selectByExample(ImProductChangeDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_product_change_detail
     *
     * @mbggenerated Wed Mar 01 18:17:01 CST 2017
     */
    ImProductChangeDetail selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_product_change_detail
     *
     * @mbggenerated Wed Mar 01 18:17:01 CST 2017
     */
    int updateByExampleSelective(@Param("record") ImProductChangeDetail record, @Param("example") ImProductChangeDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_product_change_detail
     *
     * @mbggenerated Wed Mar 01 18:17:01 CST 2017
     */
    int updateByExample(@Param("record") ImProductChangeDetail record, @Param("example") ImProductChangeDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_product_change_detail
     *
     * @mbggenerated Wed Mar 01 18:17:01 CST 2017
     */
    int updateByPrimaryKeySelective(ImProductChangeDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_product_change_detail
     *
     * @mbggenerated Wed Mar 01 18:17:01 CST 2017
     */
    int updateByPrimaryKey(ImProductChangeDetail record);
}