package com.app.market.dao.entity.agent.mybatis;

public class AgentPointsChangeDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_points_change_detail.id
     *
     * @mbggenerated Mon Mar 13 18:25:35 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_points_change_detail.bill_id
     *
     * @mbggenerated Mon Mar 13 18:25:35 CST 2017
     */
    private String billId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_points_change_detail.user_id
     *
     * @mbggenerated Mon Mar 13 18:25:35 CST 2017
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_points_change_detail.points
     *
     * @mbggenerated Mon Mar 13 18:25:35 CST 2017
     */
    private Integer points;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_points_change_detail.id
     *
     * @return the value of agent_points_change_detail.id
     *
     * @mbggenerated Mon Mar 13 18:25:35 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_points_change_detail.id
     *
     * @param id the value for agent_points_change_detail.id
     *
     * @mbggenerated Mon Mar 13 18:25:35 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_points_change_detail.bill_id
     *
     * @return the value of agent_points_change_detail.bill_id
     *
     * @mbggenerated Mon Mar 13 18:25:35 CST 2017
     */
    public String getBillId() {
        return billId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_points_change_detail.bill_id
     *
     * @param billId the value for agent_points_change_detail.bill_id
     *
     * @mbggenerated Mon Mar 13 18:25:35 CST 2017
     */
    public void setBillId(String billId) {
        this.billId = billId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_points_change_detail.user_id
     *
     * @return the value of agent_points_change_detail.user_id
     *
     * @mbggenerated Mon Mar 13 18:25:35 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_points_change_detail.user_id
     *
     * @param userId the value for agent_points_change_detail.user_id
     *
     * @mbggenerated Mon Mar 13 18:25:35 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_points_change_detail.points
     *
     * @return the value of agent_points_change_detail.points
     *
     * @mbggenerated Mon Mar 13 18:25:35 CST 2017
     */
    public Integer getPoints() {
        return points;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_points_change_detail.points
     *
     * @param points the value for agent_points_change_detail.points
     *
     * @mbggenerated Mon Mar 13 18:25:35 CST 2017
     */
    public void setPoints(Integer points) {
        this.points = points;
    }
}