package com.app.market.dao.entity.im.mybatis;

public class ImProductChangeDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_product_change_detail.id
     *
     * @mbggenerated Wed Mar 01 18:17:01 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_product_change_detail.bill_id
     *
     * @mbggenerated Wed Mar 01 18:17:01 CST 2017
     */
    private String billId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_product_change_detail.product_id
     *
     * @mbggenerated Wed Mar 01 18:17:01 CST 2017
     */
    private String productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_product_change_detail.qty
     *
     * @mbggenerated Wed Mar 01 18:17:01 CST 2017
     */
    private Integer qty;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_product_change_detail.id
     *
     * @return the value of im_product_change_detail.id
     *
     * @mbggenerated Wed Mar 01 18:17:01 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_product_change_detail.id
     *
     * @param id the value for im_product_change_detail.id
     *
     * @mbggenerated Wed Mar 01 18:17:01 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_product_change_detail.bill_id
     *
     * @return the value of im_product_change_detail.bill_id
     *
     * @mbggenerated Wed Mar 01 18:17:01 CST 2017
     */
    public String getBillId() {
        return billId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_product_change_detail.bill_id
     *
     * @param billId the value for im_product_change_detail.bill_id
     *
     * @mbggenerated Wed Mar 01 18:17:01 CST 2017
     */
    public void setBillId(String billId) {
        this.billId = billId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_product_change_detail.product_id
     *
     * @return the value of im_product_change_detail.product_id
     *
     * @mbggenerated Wed Mar 01 18:17:01 CST 2017
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_product_change_detail.product_id
     *
     * @param productId the value for im_product_change_detail.product_id
     *
     * @mbggenerated Wed Mar 01 18:17:01 CST 2017
     */
    public void setProductId(String productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_product_change_detail.qty
     *
     * @return the value of im_product_change_detail.qty
     *
     * @mbggenerated Wed Mar 01 18:17:01 CST 2017
     */
    public Integer getQty() {
        return qty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_product_change_detail.qty
     *
     * @param qty the value for im_product_change_detail.qty
     *
     * @mbggenerated Wed Mar 01 18:17:01 CST 2017
     */
    public void setQty(Integer qty) {
        this.qty = qty;
    }
}