package com.app.market.dao.entity.im.mybatis;

public class ImProductChange {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_product_change.id
     *
     * @mbggenerated Thu Mar 02 15:30:01 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_product_change.title
     *
     * @mbggenerated Thu Mar 02 15:30:01 CST 2017
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_product_change.remark
     *
     * @mbggenerated Thu Mar 02 15:30:01 CST 2017
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_product_change.status
     *
     * @mbggenerated Thu Mar 02 15:30:01 CST 2017
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_product_change.org_id
     *
     * @mbggenerated Thu Mar 02 15:30:01 CST 2017
     */
    private String orgId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_product_change.id
     *
     * @return the value of im_product_change.id
     *
     * @mbggenerated Thu Mar 02 15:30:01 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_product_change.id
     *
     * @param id the value for im_product_change.id
     *
     * @mbggenerated Thu Mar 02 15:30:01 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_product_change.title
     *
     * @return the value of im_product_change.title
     *
     * @mbggenerated Thu Mar 02 15:30:01 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_product_change.title
     *
     * @param title the value for im_product_change.title
     *
     * @mbggenerated Thu Mar 02 15:30:01 CST 2017
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_product_change.remark
     *
     * @return the value of im_product_change.remark
     *
     * @mbggenerated Thu Mar 02 15:30:01 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_product_change.remark
     *
     * @param remark the value for im_product_change.remark
     *
     * @mbggenerated Thu Mar 02 15:30:01 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_product_change.status
     *
     * @return the value of im_product_change.status
     *
     * @mbggenerated Thu Mar 02 15:30:01 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_product_change.status
     *
     * @param status the value for im_product_change.status
     *
     * @mbggenerated Thu Mar 02 15:30:01 CST 2017
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_product_change.org_id
     *
     * @return the value of im_product_change.org_id
     *
     * @mbggenerated Thu Mar 02 15:30:01 CST 2017
     */
    public String getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_product_change.org_id
     *
     * @param orgId the value for im_product_change.org_id
     *
     * @mbggenerated Thu Mar 02 15:30:01 CST 2017
     */
    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }
}