package com.app.market.dao.entity.im.mybatis;

public class ImProductInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_product_info.id
     *
     * @mbggenerated Wed Mar 01 17:10:45 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_product_info.name
     *
     * @mbggenerated Wed Mar 01 17:10:45 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_product_info.serial_num
     *
     * @mbggenerated Wed Mar 01 17:10:45 CST 2017
     */
    private String serialNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_product_info.self_num
     *
     * @mbggenerated Wed Mar 01 17:10:45 CST 2017
     */
    private String selfNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_product_info.depict
     *
     * @mbggenerated Wed Mar 01 17:10:45 CST 2017
     */
    private String depict;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_product_info.remark
     *
     * @mbggenerated Wed Mar 01 17:10:45 CST 2017
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_product_info.status
     *
     * @mbggenerated Wed Mar 01 17:10:45 CST 2017
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_product_info.org_id
     *
     * @mbggenerated Wed Mar 01 17:10:45 CST 2017
     */
    private String orgId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_product_info.id
     *
     * @return the value of im_product_info.id
     *
     * @mbggenerated Wed Mar 01 17:10:45 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_product_info.id
     *
     * @param id the value for im_product_info.id
     *
     * @mbggenerated Wed Mar 01 17:10:45 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_product_info.name
     *
     * @return the value of im_product_info.name
     *
     * @mbggenerated Wed Mar 01 17:10:45 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_product_info.name
     *
     * @param name the value for im_product_info.name
     *
     * @mbggenerated Wed Mar 01 17:10:45 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_product_info.serial_num
     *
     * @return the value of im_product_info.serial_num
     *
     * @mbggenerated Wed Mar 01 17:10:45 CST 2017
     */
    public String getSerialNum() {
        return serialNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_product_info.serial_num
     *
     * @param serialNum the value for im_product_info.serial_num
     *
     * @mbggenerated Wed Mar 01 17:10:45 CST 2017
     */
    public void setSerialNum(String serialNum) {
        this.serialNum = serialNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_product_info.self_num
     *
     * @return the value of im_product_info.self_num
     *
     * @mbggenerated Wed Mar 01 17:10:45 CST 2017
     */
    public String getSelfNum() {
        return selfNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_product_info.self_num
     *
     * @param selfNum the value for im_product_info.self_num
     *
     * @mbggenerated Wed Mar 01 17:10:45 CST 2017
     */
    public void setSelfNum(String selfNum) {
        this.selfNum = selfNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_product_info.depict
     *
     * @return the value of im_product_info.depict
     *
     * @mbggenerated Wed Mar 01 17:10:45 CST 2017
     */
    public String getDepict() {
        return depict;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_product_info.depict
     *
     * @param depict the value for im_product_info.depict
     *
     * @mbggenerated Wed Mar 01 17:10:45 CST 2017
     */
    public void setDepict(String depict) {
        this.depict = depict;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_product_info.remark
     *
     * @return the value of im_product_info.remark
     *
     * @mbggenerated Wed Mar 01 17:10:45 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_product_info.remark
     *
     * @param remark the value for im_product_info.remark
     *
     * @mbggenerated Wed Mar 01 17:10:45 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_product_info.status
     *
     * @return the value of im_product_info.status
     *
     * @mbggenerated Wed Mar 01 17:10:45 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_product_info.status
     *
     * @param status the value for im_product_info.status
     *
     * @mbggenerated Wed Mar 01 17:10:45 CST 2017
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_product_info.org_id
     *
     * @return the value of im_product_info.org_id
     *
     * @mbggenerated Wed Mar 01 17:10:45 CST 2017
     */
    public String getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_product_info.org_id
     *
     * @param orgId the value for im_product_info.org_id
     *
     * @mbggenerated Wed Mar 01 17:10:45 CST 2017
     */
    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }
}