package com.app.market.dao.mapper.sys.mybatis;

import com.app.market.dao.entity.sys.mybatis.MgOrgRegister;
import com.app.market.dao.entity.sys.mybatis.MgOrgRegisterExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MgOrgRegisterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_org_register
     *
     * @mbggenerated Sat Feb 25 11:04:51 CST 2017
     */
    int countByExample(MgOrgRegisterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_org_register
     *
     * @mbggenerated Sat Feb 25 11:04:51 CST 2017
     */
    int deleteByExample(MgOrgRegisterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_org_register
     *
     * @mbggenerated Sat Feb 25 11:04:51 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_org_register
     *
     * @mbggenerated Sat Feb 25 11:04:51 CST 2017
     */
    int insert(MgOrgRegister record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_org_register
     *
     * @mbggenerated Sat Feb 25 11:04:52 CST 2017
     */
    int insertSelective(MgOrgRegister record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_org_register
     *
     * @mbggenerated Sat Feb 25 11:04:52 CST 2017
     */
    List<MgOrgRegister> selectByExample(MgOrgRegisterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_org_register
     *
     * @mbggenerated Sat Feb 25 11:04:52 CST 2017
     */
    MgOrgRegister selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_org_register
     *
     * @mbggenerated Sat Feb 25 11:04:52 CST 2017
     */
    int updateByExampleSelective(@Param("record") MgOrgRegister record, @Param("example") MgOrgRegisterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_org_register
     *
     * @mbggenerated Sat Feb 25 11:04:52 CST 2017
     */
    int updateByExample(@Param("record") MgOrgRegister record, @Param("example") MgOrgRegisterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_org_register
     *
     * @mbggenerated Sat Feb 25 11:04:52 CST 2017
     */
    int updateByPrimaryKeySelective(MgOrgRegister record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_org_register
     *
     * @mbggenerated Sat Feb 25 11:04:52 CST 2017
     */
    int updateByPrimaryKey(MgOrgRegister record);
}