package com.app.market.dao.mapper.sys.mybatis;

import com.app.market.dao.entity.sys.mybatis.SysAuth;
import com.app.market.dao.entity.sys.mybatis.SysAuthExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysAuthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_auth
     *
     * @mbggenerated Tue Feb 21 11:50:44 CST 2017
     */
    int countByExample(SysAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_auth
     *
     * @mbggenerated Tue Feb 21 11:50:44 CST 2017
     */
    int deleteByExample(SysAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_auth
     *
     * @mbggenerated Tue Feb 21 11:50:44 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_auth
     *
     * @mbggenerated Tue Feb 21 11:50:44 CST 2017
     */
    int insert(SysAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_auth
     *
     * @mbggenerated Tue Feb 21 11:50:44 CST 2017
     */
    int insertSelective(SysAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_auth
     *
     * @mbggenerated Tue Feb 21 11:50:44 CST 2017
     */
    List<SysAuth> selectByExample(SysAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_auth
     *
     * @mbggenerated Tue Feb 21 11:50:44 CST 2017
     */
    SysAuth selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_auth
     *
     * @mbggenerated Tue Feb 21 11:50:44 CST 2017
     */
    int updateByExampleSelective(@Param("record") SysAuth record, @Param("example") SysAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_auth
     *
     * @mbggenerated Tue Feb 21 11:50:44 CST 2017
     */
    int updateByExample(@Param("record") SysAuth record, @Param("example") SysAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_auth
     *
     * @mbggenerated Tue Feb 21 11:50:44 CST 2017
     */
    int updateByPrimaryKeySelective(SysAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_auth
     *
     * @mbggenerated Tue Feb 21 11:50:44 CST 2017
     */
    int updateByPrimaryKey(SysAuth record);
}