package com.app.market.dao.mapper.sys.mybatis;

import com.app.market.dao.entity.sys.mybatis.SysApprovalConfig;
import com.app.market.dao.entity.sys.mybatis.SysApprovalConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysApprovalConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_approval_config
     *
     * @mbggenerated Mon Feb 27 15:08:41 CST 2017
     */
    int countByExample(SysApprovalConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_approval_config
     *
     * @mbggenerated Mon Feb 27 15:08:41 CST 2017
     */
    int deleteByExample(SysApprovalConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_approval_config
     *
     * @mbggenerated Mon Feb 27 15:08:41 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_approval_config
     *
     * @mbggenerated Mon Feb 27 15:08:41 CST 2017
     */
    int insert(SysApprovalConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_approval_config
     *
     * @mbggenerated Mon Feb 27 15:08:41 CST 2017
     */
    int insertSelective(SysApprovalConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_approval_config
     *
     * @mbggenerated Mon Feb 27 15:08:41 CST 2017
     */
    List<SysApprovalConfig> selectByExample(SysApprovalConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_approval_config
     *
     * @mbggenerated Mon Feb 27 15:08:41 CST 2017
     */
    SysApprovalConfig selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_approval_config
     *
     * @mbggenerated Mon Feb 27 15:08:41 CST 2017
     */
    int updateByExampleSelective(@Param("record") SysApprovalConfig record, @Param("example") SysApprovalConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_approval_config
     *
     * @mbggenerated Mon Feb 27 15:08:41 CST 2017
     */
    int updateByExample(@Param("record") SysApprovalConfig record, @Param("example") SysApprovalConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_approval_config
     *
     * @mbggenerated Mon Feb 27 15:08:41 CST 2017
     */
    int updateByPrimaryKeySelective(SysApprovalConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_approval_config
     *
     * @mbggenerated Mon Feb 27 15:08:41 CST 2017
     */
    int updateByPrimaryKey(SysApprovalConfig record);
}