package com.app.market.dao.mapper.sys.mybatis;

import com.app.market.dao.entity.sys.mybatis.SysDic;
import com.app.market.dao.entity.sys.mybatis.SysDicExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysDicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dic
     *
     * @mbggenerated Tue Feb 21 09:17:58 CST 2017
     */
    int countByExample(SysDicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dic
     *
     * @mbggenerated Tue Feb 21 09:17:58 CST 2017
     */
    int deleteByExample(SysDicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dic
     *
     * @mbggenerated Tue Feb 21 09:17:58 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dic
     *
     * @mbggenerated Tue Feb 21 09:17:58 CST 2017
     */
    int insert(SysDic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dic
     *
     * @mbggenerated Tue Feb 21 09:17:58 CST 2017
     */
    int insertSelective(SysDic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dic
     *
     * @mbggenerated Tue Feb 21 09:17:58 CST 2017
     */
    List<SysDic> selectByExample(SysDicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dic
     *
     * @mbggenerated Tue Feb 21 09:17:58 CST 2017
     */
    SysDic selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dic
     *
     * @mbggenerated Tue Feb 21 09:17:58 CST 2017
     */
    int updateByExampleSelective(@Param("record") SysDic record, @Param("example") SysDicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dic
     *
     * @mbggenerated Tue Feb 21 09:17:58 CST 2017
     */
    int updateByExample(@Param("record") SysDic record, @Param("example") SysDicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dic
     *
     * @mbggenerated Tue Feb 21 09:17:58 CST 2017
     */
    int updateByPrimaryKeySelective(SysDic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dic
     *
     * @mbggenerated Tue Feb 21 09:17:58 CST 2017
     */
    int updateByPrimaryKey(SysDic record);
}