package com.app.market.dao.mapper.sys.mybatis;

import com.app.market.dao.entity.sys.mybatis.SysOrg;
import com.app.market.dao.entity.sys.mybatis.SysOrgExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysOrgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org
     *
     * @mbggenerated Wed Mar 01 09:26:09 CST 2017
     */
    int countByExample(SysOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org
     *
     * @mbggenerated Wed Mar 01 09:26:09 CST 2017
     */
    int deleteByExample(SysOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org
     *
     * @mbggenerated Wed Mar 01 09:26:09 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org
     *
     * @mbggenerated Wed Mar 01 09:26:09 CST 2017
     */
    int insert(SysOrg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org
     *
     * @mbggenerated Wed Mar 01 09:26:09 CST 2017
     */
    int insertSelective(SysOrg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org
     *
     * @mbggenerated Wed Mar 01 09:26:09 CST 2017
     */
    List<SysOrg> selectByExample(SysOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org
     *
     * @mbggenerated Wed Mar 01 09:26:09 CST 2017
     */
    SysOrg selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org
     *
     * @mbggenerated Wed Mar 01 09:26:09 CST 2017
     */
    int updateByExampleSelective(@Param("record") SysOrg record, @Param("example") SysOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org
     *
     * @mbggenerated Wed Mar 01 09:26:09 CST 2017
     */
    int updateByExample(@Param("record") SysOrg record, @Param("example") SysOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org
     *
     * @mbggenerated Wed Mar 01 09:26:09 CST 2017
     */
    int updateByPrimaryKeySelective(SysOrg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org
     *
     * @mbggenerated Wed Mar 01 09:26:09 CST 2017
     */
    int updateByPrimaryKey(SysOrg record);
}