package com.app.market.dao.mapper.sys.mybatis;

import com.app.market.dao.entity.sys.mybatis.SysOrgAuth;
import com.app.market.dao.entity.sys.mybatis.SysOrgAuthExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysOrgAuthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org_auth
     *
     * @mbggenerated Wed Feb 22 10:21:25 CST 2017
     */
    int countByExample(SysOrgAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org_auth
     *
     * @mbggenerated Wed Feb 22 10:21:25 CST 2017
     */
    int deleteByExample(SysOrgAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org_auth
     *
     * @mbggenerated Wed Feb 22 10:21:25 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org_auth
     *
     * @mbggenerated Wed Feb 22 10:21:25 CST 2017
     */
    int insert(SysOrgAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org_auth
     *
     * @mbggenerated Wed Feb 22 10:21:25 CST 2017
     */
    int insertSelective(SysOrgAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org_auth
     *
     * @mbggenerated Wed Feb 22 10:21:25 CST 2017
     */
    List<SysOrgAuth> selectByExample(SysOrgAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org_auth
     *
     * @mbggenerated Wed Feb 22 10:21:25 CST 2017
     */
    SysOrgAuth selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org_auth
     *
     * @mbggenerated Wed Feb 22 10:21:25 CST 2017
     */
    int updateByExampleSelective(@Param("record") SysOrgAuth record, @Param("example") SysOrgAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org_auth
     *
     * @mbggenerated Wed Feb 22 10:21:25 CST 2017
     */
    int updateByExample(@Param("record") SysOrgAuth record, @Param("example") SysOrgAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org_auth
     *
     * @mbggenerated Wed Feb 22 10:21:25 CST 2017
     */
    int updateByPrimaryKeySelective(SysOrgAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org_auth
     *
     * @mbggenerated Wed Feb 22 10:21:25 CST 2017
     */
    int updateByPrimaryKey(SysOrgAuth record);
}