package com.app.market.dao.mapper.sys.mybatis;

import com.app.market.dao.entity.sys.mybatis.SysTimeList;
import com.app.market.dao.entity.sys.mybatis.SysTimeListExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysTimeListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_time_list
     *
     * @mbggenerated Tue Feb 28 11:18:06 CST 2017
     */
    int countByExample(SysTimeListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_time_list
     *
     * @mbggenerated Tue Feb 28 11:18:06 CST 2017
     */
    int deleteByExample(SysTimeListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_time_list
     *
     * @mbggenerated Tue Feb 28 11:18:06 CST 2017
     */
    int deleteByPrimaryKey(String billId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_time_list
     *
     * @mbggenerated Tue Feb 28 11:18:06 CST 2017
     */
    int insert(SysTimeList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_time_list
     *
     * @mbggenerated Tue Feb 28 11:18:06 CST 2017
     */
    int insertSelective(SysTimeList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_time_list
     *
     * @mbggenerated Tue Feb 28 11:18:06 CST 2017
     */
    List<SysTimeList> selectByExample(SysTimeListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_time_list
     *
     * @mbggenerated Tue Feb 28 11:18:06 CST 2017
     */
    SysTimeList selectByPrimaryKey(String billId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_time_list
     *
     * @mbggenerated Tue Feb 28 11:18:06 CST 2017
     */
    int updateByExampleSelective(@Param("record") SysTimeList record, @Param("example") SysTimeListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_time_list
     *
     * @mbggenerated Tue Feb 28 11:18:06 CST 2017
     */
    int updateByExample(@Param("record") SysTimeList record, @Param("example") SysTimeListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_time_list
     *
     * @mbggenerated Tue Feb 28 11:18:06 CST 2017
     */
    int updateByPrimaryKeySelective(SysTimeList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_time_list
     *
     * @mbggenerated Tue Feb 28 11:18:06 CST 2017
     */
    int updateByPrimaryKey(SysTimeList record);
}