package com.app.market.dao.entity.mms.mybatis;

import java.util.Date;

public class MmsInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mms_info.id
     *
     * @mbggenerated Tue Mar 14 11:40:27 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mms_info.user_name
     *
     * @mbggenerated Tue Mar 14 11:40:27 CST 2017
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mms_info.name
     *
     * @mbggenerated Tue Mar 14 11:40:27 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mms_info.mobile
     *
     * @mbggenerated Tue Mar 14 11:40:27 CST 2017
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mms_info.end_time
     *
     * @mbggenerated Tue Mar 14 11:40:27 CST 2017
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mms_info.address
     *
     * @mbggenerated Tue Mar 14 11:40:27 CST 2017
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mms_info.status
     *
     * @mbggenerated Tue Mar 14 11:40:27 CST 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mms_info.points
     *
     * @mbggenerated Tue Mar 14 11:40:27 CST 2017
     */
    private Integer points;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mms_info.org_id
     *
     * @mbggenerated Tue Mar 14 11:40:27 CST 2017
     */
    private String orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mms_info.create_user
     *
     * @mbggenerated Tue Mar 14 11:40:27 CST 2017
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mms_info.create_time
     *
     * @mbggenerated Tue Mar 14 11:40:27 CST 2017
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mms_info.id
     *
     * @return the value of mms_info.id
     *
     * @mbggenerated Tue Mar 14 11:40:27 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mms_info.id
     *
     * @param id the value for mms_info.id
     *
     * @mbggenerated Tue Mar 14 11:40:27 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mms_info.user_name
     *
     * @return the value of mms_info.user_name
     *
     * @mbggenerated Tue Mar 14 11:40:27 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mms_info.user_name
     *
     * @param userName the value for mms_info.user_name
     *
     * @mbggenerated Tue Mar 14 11:40:27 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mms_info.name
     *
     * @return the value of mms_info.name
     *
     * @mbggenerated Tue Mar 14 11:40:27 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mms_info.name
     *
     * @param name the value for mms_info.name
     *
     * @mbggenerated Tue Mar 14 11:40:27 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mms_info.mobile
     *
     * @return the value of mms_info.mobile
     *
     * @mbggenerated Tue Mar 14 11:40:27 CST 2017
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mms_info.mobile
     *
     * @param mobile the value for mms_info.mobile
     *
     * @mbggenerated Tue Mar 14 11:40:27 CST 2017
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mms_info.end_time
     *
     * @return the value of mms_info.end_time
     *
     * @mbggenerated Tue Mar 14 11:40:27 CST 2017
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mms_info.end_time
     *
     * @param endTime the value for mms_info.end_time
     *
     * @mbggenerated Tue Mar 14 11:40:27 CST 2017
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mms_info.address
     *
     * @return the value of mms_info.address
     *
     * @mbggenerated Tue Mar 14 11:40:27 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mms_info.address
     *
     * @param address the value for mms_info.address
     *
     * @mbggenerated Tue Mar 14 11:40:27 CST 2017
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mms_info.status
     *
     * @return the value of mms_info.status
     *
     * @mbggenerated Tue Mar 14 11:40:27 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mms_info.status
     *
     * @param status the value for mms_info.status
     *
     * @mbggenerated Tue Mar 14 11:40:27 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mms_info.points
     *
     * @return the value of mms_info.points
     *
     * @mbggenerated Tue Mar 14 11:40:27 CST 2017
     */
    public Integer getPoints() {
        return points;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mms_info.points
     *
     * @param points the value for mms_info.points
     *
     * @mbggenerated Tue Mar 14 11:40:27 CST 2017
     */
    public void setPoints(Integer points) {
        this.points = points;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mms_info.org_id
     *
     * @return the value of mms_info.org_id
     *
     * @mbggenerated Tue Mar 14 11:40:27 CST 2017
     */
    public String getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mms_info.org_id
     *
     * @param orgId the value for mms_info.org_id
     *
     * @mbggenerated Tue Mar 14 11:40:27 CST 2017
     */
    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mms_info.create_user
     *
     * @return the value of mms_info.create_user
     *
     * @mbggenerated Tue Mar 14 11:40:27 CST 2017
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mms_info.create_user
     *
     * @param createUser the value for mms_info.create_user
     *
     * @mbggenerated Tue Mar 14 11:40:27 CST 2017
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mms_info.create_time
     *
     * @return the value of mms_info.create_time
     *
     * @mbggenerated Tue Mar 14 11:40:27 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mms_info.create_time
     *
     * @param createTime the value for mms_info.create_time
     *
     * @mbggenerated Tue Mar 14 11:40:27 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}