package com.app.market.dao.entity.mms.mybatis;

public class MmsPointsChangeDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mms_points_change_detail.id
     *
     * @mbggenerated Fri Mar 10 16:25:50 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mms_points_change_detail.bill_id
     *
     * @mbggenerated Fri Mar 10 16:25:50 CST 2017
     */
    private String billId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mms_points_change_detail.info_id
     *
     * @mbggenerated Fri Mar 10 16:25:50 CST 2017
     */
    private String infoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mms_points_change_detail.points
     *
     * @mbggenerated Fri Mar 10 16:25:50 CST 2017
     */
    private Integer points;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mms_points_change_detail.id
     *
     * @return the value of mms_points_change_detail.id
     *
     * @mbggenerated Fri Mar 10 16:25:50 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mms_points_change_detail.id
     *
     * @param id the value for mms_points_change_detail.id
     *
     * @mbggenerated Fri Mar 10 16:25:50 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mms_points_change_detail.bill_id
     *
     * @return the value of mms_points_change_detail.bill_id
     *
     * @mbggenerated Fri Mar 10 16:25:50 CST 2017
     */
    public String getBillId() {
        return billId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mms_points_change_detail.bill_id
     *
     * @param billId the value for mms_points_change_detail.bill_id
     *
     * @mbggenerated Fri Mar 10 16:25:50 CST 2017
     */
    public void setBillId(String billId) {
        this.billId = billId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mms_points_change_detail.info_id
     *
     * @return the value of mms_points_change_detail.info_id
     *
     * @mbggenerated Fri Mar 10 16:25:50 CST 2017
     */
    public String getInfoId() {
        return infoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mms_points_change_detail.info_id
     *
     * @param infoId the value for mms_points_change_detail.info_id
     *
     * @mbggenerated Fri Mar 10 16:25:50 CST 2017
     */
    public void setInfoId(String infoId) {
        this.infoId = infoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mms_points_change_detail.points
     *
     * @return the value of mms_points_change_detail.points
     *
     * @mbggenerated Fri Mar 10 16:25:50 CST 2017
     */
    public Integer getPoints() {
        return points;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mms_points_change_detail.points
     *
     * @param points the value for mms_points_change_detail.points
     *
     * @mbggenerated Fri Mar 10 16:25:50 CST 2017
     */
    public void setPoints(Integer points) {
        this.points = points;
    }
}