package com.app.market.dao.entity.oa.mybatis;

import java.util.Date;

public class OaAttendance {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_attendance.id
     *
     * @mbggenerated Tue Mar 21 13:36:26 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_attendance.user_id
     *
     * @mbggenerated Tue Mar 21 13:36:26 CST 2017
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_attendance.begin_time
     *
     * @mbggenerated Tue Mar 21 13:36:26 CST 2017
     */
    private Date beginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_attendance.end_time
     *
     * @mbggenerated Tue Mar 21 13:36:26 CST 2017
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_attendance.org_id
     *
     * @mbggenerated Tue Mar 21 13:36:26 CST 2017
     */
    private String orgId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_attendance.id
     *
     * @return the value of oa_attendance.id
     *
     * @mbggenerated Tue Mar 21 13:36:26 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_attendance.id
     *
     * @param id the value for oa_attendance.id
     *
     * @mbggenerated Tue Mar 21 13:36:26 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_attendance.user_id
     *
     * @return the value of oa_attendance.user_id
     *
     * @mbggenerated Tue Mar 21 13:36:26 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_attendance.user_id
     *
     * @param userId the value for oa_attendance.user_id
     *
     * @mbggenerated Tue Mar 21 13:36:26 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_attendance.begin_time
     *
     * @return the value of oa_attendance.begin_time
     *
     * @mbggenerated Tue Mar 21 13:36:26 CST 2017
     */
    public Date getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_attendance.begin_time
     *
     * @param beginTime the value for oa_attendance.begin_time
     *
     * @mbggenerated Tue Mar 21 13:36:26 CST 2017
     */
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_attendance.end_time
     *
     * @return the value of oa_attendance.end_time
     *
     * @mbggenerated Tue Mar 21 13:36:26 CST 2017
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_attendance.end_time
     *
     * @param endTime the value for oa_attendance.end_time
     *
     * @mbggenerated Tue Mar 21 13:36:26 CST 2017
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_attendance.org_id
     *
     * @return the value of oa_attendance.org_id
     *
     * @mbggenerated Tue Mar 21 13:36:26 CST 2017
     */
    public String getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_attendance.org_id
     *
     * @param orgId the value for oa_attendance.org_id
     *
     * @mbggenerated Tue Mar 21 13:36:26 CST 2017
     */
    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }
}