package com.app.market.dao.entity.oa.mybatis;

public class OaNotice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_notice.id
     *
     * @mbggenerated Fri Mar 17 09:20:55 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_notice.title
     *
     * @mbggenerated Fri Mar 17 09:20:55 CST 2017
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_notice.content
     *
     * @mbggenerated Fri Mar 17 09:20:55 CST 2017
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_notice.status
     *
     * @mbggenerated Fri Mar 17 09:20:55 CST 2017
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_notice.org_id
     *
     * @mbggenerated Fri Mar 17 09:20:55 CST 2017
     */
    private String orgId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_notice.id
     *
     * @return the value of oa_notice.id
     *
     * @mbggenerated Fri Mar 17 09:20:55 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_notice.id
     *
     * @param id the value for oa_notice.id
     *
     * @mbggenerated Fri Mar 17 09:20:55 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_notice.title
     *
     * @return the value of oa_notice.title
     *
     * @mbggenerated Fri Mar 17 09:20:55 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_notice.title
     *
     * @param title the value for oa_notice.title
     *
     * @mbggenerated Fri Mar 17 09:20:55 CST 2017
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_notice.content
     *
     * @return the value of oa_notice.content
     *
     * @mbggenerated Fri Mar 17 09:20:55 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_notice.content
     *
     * @param content the value for oa_notice.content
     *
     * @mbggenerated Fri Mar 17 09:20:55 CST 2017
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_notice.status
     *
     * @return the value of oa_notice.status
     *
     * @mbggenerated Fri Mar 17 09:20:55 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_notice.status
     *
     * @param status the value for oa_notice.status
     *
     * @mbggenerated Fri Mar 17 09:20:55 CST 2017
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_notice.org_id
     *
     * @return the value of oa_notice.org_id
     *
     * @mbggenerated Fri Mar 17 09:20:55 CST 2017
     */
    public String getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_notice.org_id
     *
     * @param orgId the value for oa_notice.org_id
     *
     * @mbggenerated Fri Mar 17 09:20:55 CST 2017
     */
    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }
}