package com.app.market.dao.mapper.asset.mybatis;

import com.app.market.dao.entity.asset.mybatis.AssetRegister;
import com.app.market.dao.entity.asset.mybatis.AssetRegisterExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AssetRegisterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_register
     *
     * @mbggenerated Mon Mar 27 09:36:45 CST 2017
     */
    int countByExample(AssetRegisterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_register
     *
     * @mbggenerated Mon Mar 27 09:36:45 CST 2017
     */
    int deleteByExample(AssetRegisterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_register
     *
     * @mbggenerated Mon Mar 27 09:36:45 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_register
     *
     * @mbggenerated Mon Mar 27 09:36:45 CST 2017
     */
    int insert(AssetRegister record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_register
     *
     * @mbggenerated Mon Mar 27 09:36:45 CST 2017
     */
    int insertSelective(AssetRegister record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_register
     *
     * @mbggenerated Mon Mar 27 09:36:45 CST 2017
     */
    List<AssetRegister> selectByExample(AssetRegisterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_register
     *
     * @mbggenerated Mon Mar 27 09:36:45 CST 2017
     */
    AssetRegister selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_register
     *
     * @mbggenerated Mon Mar 27 09:36:45 CST 2017
     */
    int updateByExampleSelective(@Param("record") AssetRegister record, @Param("example") AssetRegisterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_register
     *
     * @mbggenerated Mon Mar 27 09:36:45 CST 2017
     */
    int updateByExample(@Param("record") AssetRegister record, @Param("example") AssetRegisterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_register
     *
     * @mbggenerated Mon Mar 27 09:36:45 CST 2017
     */
    int updateByPrimaryKeySelective(AssetRegister record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_register
     *
     * @mbggenerated Mon Mar 27 09:36:45 CST 2017
     */
    int updateByPrimaryKey(AssetRegister record);
}