package com.app.market.dao.entity.sys.mybatis;

public class MgOrgAuth {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mg_org_auth.id
     *
     * @mbggenerated Tue Feb 28 11:46:24 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mg_org_auth.org_id
     *
     * @mbggenerated Tue Feb 28 11:46:24 CST 2017
     */
    private String orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mg_org_auth.auth_type
     *
     * @mbggenerated Tue Feb 28 11:46:24 CST 2017
     */
    private String authType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mg_org_auth.status
     *
     * @mbggenerated Tue Feb 28 11:46:24 CST 2017
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mg_org_auth.id
     *
     * @return the value of mg_org_auth.id
     *
     * @mbggenerated Tue Feb 28 11:46:24 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mg_org_auth.id
     *
     * @param id the value for mg_org_auth.id
     *
     * @mbggenerated Tue Feb 28 11:46:24 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mg_org_auth.org_id
     *
     * @return the value of mg_org_auth.org_id
     *
     * @mbggenerated Tue Feb 28 11:46:24 CST 2017
     */
    public String getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mg_org_auth.org_id
     *
     * @param orgId the value for mg_org_auth.org_id
     *
     * @mbggenerated Tue Feb 28 11:46:24 CST 2017
     */
    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mg_org_auth.auth_type
     *
     * @return the value of mg_org_auth.auth_type
     *
     * @mbggenerated Tue Feb 28 11:46:24 CST 2017
     */
    public String getAuthType() {
        return authType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mg_org_auth.auth_type
     *
     * @param authType the value for mg_org_auth.auth_type
     *
     * @mbggenerated Tue Feb 28 11:46:24 CST 2017
     */
    public void setAuthType(String authType) {
        this.authType = authType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mg_org_auth.status
     *
     * @return the value of mg_org_auth.status
     *
     * @mbggenerated Tue Feb 28 11:46:24 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mg_org_auth.status
     *
     * @param status the value for mg_org_auth.status
     *
     * @mbggenerated Tue Feb 28 11:46:24 CST 2017
     */
    public void setStatus(String status) {
        this.status = status;
    }
}