package com.app.market.dao.entity.sys.mybatis;

public class MgOrgRegister {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mg_org_register.id
     *
     * @mbggenerated Mon Feb 27 14:50:43 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mg_org_register.name
     *
     * @mbggenerated Mon Feb 27 14:50:43 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mg_org_register.address
     *
     * @mbggenerated Mon Feb 27 14:50:43 CST 2017
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mg_org_register.contact
     *
     * @mbggenerated Mon Feb 27 14:50:43 CST 2017
     */
    private String contact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mg_org_register.mobile
     *
     * @mbggenerated Mon Feb 27 14:50:43 CST 2017
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mg_org_register.flag
     *
     * @mbggenerated Mon Feb 27 14:50:43 CST 2017
     */
    private String flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mg_org_register.create_user
     *
     * @mbggenerated Mon Feb 27 14:50:43 CST 2017
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mg_org_register.update_user
     *
     * @mbggenerated Mon Feb 27 14:50:43 CST 2017
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mg_org_register.status
     *
     * @mbggenerated Mon Feb 27 14:50:43 CST 2017
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mg_org_register.remark
     *
     * @mbggenerated Mon Feb 27 14:50:43 CST 2017
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mg_org_register.id
     *
     * @return the value of mg_org_register.id
     *
     * @mbggenerated Mon Feb 27 14:50:43 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mg_org_register.id
     *
     * @param id the value for mg_org_register.id
     *
     * @mbggenerated Mon Feb 27 14:50:43 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mg_org_register.name
     *
     * @return the value of mg_org_register.name
     *
     * @mbggenerated Mon Feb 27 14:50:43 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mg_org_register.name
     *
     * @param name the value for mg_org_register.name
     *
     * @mbggenerated Mon Feb 27 14:50:43 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mg_org_register.address
     *
     * @return the value of mg_org_register.address
     *
     * @mbggenerated Mon Feb 27 14:50:43 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mg_org_register.address
     *
     * @param address the value for mg_org_register.address
     *
     * @mbggenerated Mon Feb 27 14:50:43 CST 2017
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mg_org_register.contact
     *
     * @return the value of mg_org_register.contact
     *
     * @mbggenerated Mon Feb 27 14:50:43 CST 2017
     */
    public String getContact() {
        return contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mg_org_register.contact
     *
     * @param contact the value for mg_org_register.contact
     *
     * @mbggenerated Mon Feb 27 14:50:43 CST 2017
     */
    public void setContact(String contact) {
        this.contact = contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mg_org_register.mobile
     *
     * @return the value of mg_org_register.mobile
     *
     * @mbggenerated Mon Feb 27 14:50:43 CST 2017
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mg_org_register.mobile
     *
     * @param mobile the value for mg_org_register.mobile
     *
     * @mbggenerated Mon Feb 27 14:50:43 CST 2017
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mg_org_register.flag
     *
     * @return the value of mg_org_register.flag
     *
     * @mbggenerated Mon Feb 27 14:50:43 CST 2017
     */
    public String getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mg_org_register.flag
     *
     * @param flag the value for mg_org_register.flag
     *
     * @mbggenerated Mon Feb 27 14:50:43 CST 2017
     */
    public void setFlag(String flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mg_org_register.create_user
     *
     * @return the value of mg_org_register.create_user
     *
     * @mbggenerated Mon Feb 27 14:50:43 CST 2017
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mg_org_register.create_user
     *
     * @param createUser the value for mg_org_register.create_user
     *
     * @mbggenerated Mon Feb 27 14:50:43 CST 2017
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mg_org_register.update_user
     *
     * @return the value of mg_org_register.update_user
     *
     * @mbggenerated Mon Feb 27 14:50:43 CST 2017
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mg_org_register.update_user
     *
     * @param updateUser the value for mg_org_register.update_user
     *
     * @mbggenerated Mon Feb 27 14:50:43 CST 2017
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mg_org_register.status
     *
     * @return the value of mg_org_register.status
     *
     * @mbggenerated Mon Feb 27 14:50:43 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mg_org_register.status
     *
     * @param status the value for mg_org_register.status
     *
     * @mbggenerated Mon Feb 27 14:50:43 CST 2017
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mg_org_register.remark
     *
     * @return the value of mg_org_register.remark
     *
     * @mbggenerated Mon Feb 27 14:50:43 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mg_org_register.remark
     *
     * @param remark the value for mg_org_register.remark
     *
     * @mbggenerated Mon Feb 27 14:50:43 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}