package com.app.market.dao.entity.sys.mybatis;

import java.util.Date;

public class SysApprovalList {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_approval_list.id
     *
     * @mbggenerated Mon Feb 27 15:23:30 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_approval_list.bill_id
     *
     * @mbggenerated Mon Feb 27 15:23:30 CST 2017
     */
    private String billId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_approval_list.bill_name
     *
     * @mbggenerated Mon Feb 27 15:23:30 CST 2017
     */
    private String billName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_approval_list.create_user
     *
     * @mbggenerated Mon Feb 27 15:23:30 CST 2017
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_approval_list.create_time
     *
     * @mbggenerated Mon Feb 27 15:23:30 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_approval_list.status
     *
     * @mbggenerated Mon Feb 27 15:23:30 CST 2017
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_approval_list.remark
     *
     * @mbggenerated Mon Feb 27 15:23:30 CST 2017
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_approval_list.id
     *
     * @return the value of sys_approval_list.id
     *
     * @mbggenerated Mon Feb 27 15:23:30 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_approval_list.id
     *
     * @param id the value for sys_approval_list.id
     *
     * @mbggenerated Mon Feb 27 15:23:30 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_approval_list.bill_id
     *
     * @return the value of sys_approval_list.bill_id
     *
     * @mbggenerated Mon Feb 27 15:23:30 CST 2017
     */
    public String getBillId() {
        return billId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_approval_list.bill_id
     *
     * @param billId the value for sys_approval_list.bill_id
     *
     * @mbggenerated Mon Feb 27 15:23:30 CST 2017
     */
    public void setBillId(String billId) {
        this.billId = billId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_approval_list.bill_name
     *
     * @return the value of sys_approval_list.bill_name
     *
     * @mbggenerated Mon Feb 27 15:23:30 CST 2017
     */
    public String getBillName() {
        return billName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_approval_list.bill_name
     *
     * @param billName the value for sys_approval_list.bill_name
     *
     * @mbggenerated Mon Feb 27 15:23:30 CST 2017
     */
    public void setBillName(String billName) {
        this.billName = billName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_approval_list.create_user
     *
     * @return the value of sys_approval_list.create_user
     *
     * @mbggenerated Mon Feb 27 15:23:30 CST 2017
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_approval_list.create_user
     *
     * @param createUser the value for sys_approval_list.create_user
     *
     * @mbggenerated Mon Feb 27 15:23:30 CST 2017
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_approval_list.create_time
     *
     * @return the value of sys_approval_list.create_time
     *
     * @mbggenerated Mon Feb 27 15:23:30 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_approval_list.create_time
     *
     * @param createTime the value for sys_approval_list.create_time
     *
     * @mbggenerated Mon Feb 27 15:23:30 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_approval_list.status
     *
     * @return the value of sys_approval_list.status
     *
     * @mbggenerated Mon Feb 27 15:23:30 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_approval_list.status
     *
     * @param status the value for sys_approval_list.status
     *
     * @mbggenerated Mon Feb 27 15:23:30 CST 2017
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_approval_list.remark
     *
     * @return the value of sys_approval_list.remark
     *
     * @mbggenerated Mon Feb 27 15:23:30 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_approval_list.remark
     *
     * @param remark the value for sys_approval_list.remark
     *
     * @mbggenerated Mon Feb 27 15:23:30 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}