package com.app.market.dao.entity.sys.mybatis;

import java.util.Date;

public class SysAuth {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_auth.id
     *
     * @mbggenerated Tue Feb 21 11:50:44 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_auth.parent_id
     *
     * @mbggenerated Tue Feb 21 11:50:44 CST 2017
     */
    private String parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_auth.name
     *
     * @mbggenerated Tue Feb 21 11:50:44 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_auth.auth_type
     *
     * @mbggenerated Tue Feb 21 11:50:44 CST 2017
     */
    private String authType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_auth.auth_url
     *
     * @mbggenerated Tue Feb 21 11:50:44 CST 2017
     */
    private String authUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_auth.auth_icon
     *
     * @mbggenerated Tue Feb 21 11:50:44 CST 2017
     */
    private String authIcon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_auth.auth_value
     *
     * @mbggenerated Tue Feb 21 11:50:44 CST 2017
     */
    private String authValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_auth.mg_type
     *
     * @mbggenerated Tue Feb 21 11:50:44 CST 2017
     */
    private String mgType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_auth.is_init
     *
     * @mbggenerated Tue Feb 21 11:50:44 CST 2017
     */
    private String isInit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_auth.create_time
     *
     * @mbggenerated Tue Feb 21 11:50:44 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_auth.update_time
     *
     * @mbggenerated Tue Feb 21 11:50:44 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_auth.id
     *
     * @return the value of sys_auth.id
     *
     * @mbggenerated Tue Feb 21 11:50:44 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_auth.id
     *
     * @param id the value for sys_auth.id
     *
     * @mbggenerated Tue Feb 21 11:50:44 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_auth.parent_id
     *
     * @return the value of sys_auth.parent_id
     *
     * @mbggenerated Tue Feb 21 11:50:44 CST 2017
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_auth.parent_id
     *
     * @param parentId the value for sys_auth.parent_id
     *
     * @mbggenerated Tue Feb 21 11:50:44 CST 2017
     */
    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_auth.name
     *
     * @return the value of sys_auth.name
     *
     * @mbggenerated Tue Feb 21 11:50:44 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_auth.name
     *
     * @param name the value for sys_auth.name
     *
     * @mbggenerated Tue Feb 21 11:50:44 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_auth.auth_type
     *
     * @return the value of sys_auth.auth_type
     *
     * @mbggenerated Tue Feb 21 11:50:44 CST 2017
     */
    public String getAuthType() {
        return authType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_auth.auth_type
     *
     * @param authType the value for sys_auth.auth_type
     *
     * @mbggenerated Tue Feb 21 11:50:44 CST 2017
     */
    public void setAuthType(String authType) {
        this.authType = authType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_auth.auth_url
     *
     * @return the value of sys_auth.auth_url
     *
     * @mbggenerated Tue Feb 21 11:50:44 CST 2017
     */
    public String getAuthUrl() {
        return authUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_auth.auth_url
     *
     * @param authUrl the value for sys_auth.auth_url
     *
     * @mbggenerated Tue Feb 21 11:50:44 CST 2017
     */
    public void setAuthUrl(String authUrl) {
        this.authUrl = authUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_auth.auth_icon
     *
     * @return the value of sys_auth.auth_icon
     *
     * @mbggenerated Tue Feb 21 11:50:44 CST 2017
     */
    public String getAuthIcon() {
        return authIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_auth.auth_icon
     *
     * @param authIcon the value for sys_auth.auth_icon
     *
     * @mbggenerated Tue Feb 21 11:50:44 CST 2017
     */
    public void setAuthIcon(String authIcon) {
        this.authIcon = authIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_auth.auth_value
     *
     * @return the value of sys_auth.auth_value
     *
     * @mbggenerated Tue Feb 21 11:50:44 CST 2017
     */
    public String getAuthValue() {
        return authValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_auth.auth_value
     *
     * @param authValue the value for sys_auth.auth_value
     *
     * @mbggenerated Tue Feb 21 11:50:44 CST 2017
     */
    public void setAuthValue(String authValue) {
        this.authValue = authValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_auth.mg_type
     *
     * @return the value of sys_auth.mg_type
     *
     * @mbggenerated Tue Feb 21 11:50:44 CST 2017
     */
    public String getMgType() {
        return mgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_auth.mg_type
     *
     * @param mgType the value for sys_auth.mg_type
     *
     * @mbggenerated Tue Feb 21 11:50:44 CST 2017
     */
    public void setMgType(String mgType) {
        this.mgType = mgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_auth.is_init
     *
     * @return the value of sys_auth.is_init
     *
     * @mbggenerated Tue Feb 21 11:50:44 CST 2017
     */
    public String getIsInit() {
        return isInit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_auth.is_init
     *
     * @param isInit the value for sys_auth.is_init
     *
     * @mbggenerated Tue Feb 21 11:50:44 CST 2017
     */
    public void setIsInit(String isInit) {
        this.isInit = isInit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_auth.create_time
     *
     * @return the value of sys_auth.create_time
     *
     * @mbggenerated Tue Feb 21 11:50:44 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_auth.create_time
     *
     * @param createTime the value for sys_auth.create_time
     *
     * @mbggenerated Tue Feb 21 11:50:44 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_auth.update_time
     *
     * @return the value of sys_auth.update_time
     *
     * @mbggenerated Tue Feb 21 11:50:44 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_auth.update_time
     *
     * @param updateTime the value for sys_auth.update_time
     *
     * @mbggenerated Tue Feb 21 11:50:44 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}