package com.app.market.dao.entity.sys.mybatis;

public class SysApprovalConfig {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_approval_config.id
     *
     * @mbggenerated Mon Feb 27 15:08:41 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_approval_config.obj_name
     *
     * @mbggenerated Mon Feb 27 15:08:41 CST 2017
     */
    private String objName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_approval_config.max_status
     *
     * @mbggenerated Mon Feb 27 15:08:41 CST 2017
     */
    private String maxStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_approval_config.id
     *
     * @return the value of sys_approval_config.id
     *
     * @mbggenerated Mon Feb 27 15:08:41 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_approval_config.id
     *
     * @param id the value for sys_approval_config.id
     *
     * @mbggenerated Mon Feb 27 15:08:41 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_approval_config.obj_name
     *
     * @return the value of sys_approval_config.obj_name
     *
     * @mbggenerated Mon Feb 27 15:08:41 CST 2017
     */
    public String getObjName() {
        return objName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_approval_config.obj_name
     *
     * @param objName the value for sys_approval_config.obj_name
     *
     * @mbggenerated Mon Feb 27 15:08:41 CST 2017
     */
    public void setObjName(String objName) {
        this.objName = objName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_approval_config.max_status
     *
     * @return the value of sys_approval_config.max_status
     *
     * @mbggenerated Mon Feb 27 15:08:41 CST 2017
     */
    public String getMaxStatus() {
        return maxStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_approval_config.max_status
     *
     * @param maxStatus the value for sys_approval_config.max_status
     *
     * @mbggenerated Mon Feb 27 15:08:41 CST 2017
     */
    public void setMaxStatus(String maxStatus) {
        this.maxStatus = maxStatus;
    }
}