package com.app.market.dao.entity.sys.mybatis;

public class SysDic {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dic.id
     *
     * @mbggenerated Tue Feb 21 09:17:58 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dic.name
     *
     * @mbggenerated Tue Feb 21 09:17:58 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dic.val
     *
     * @mbggenerated Tue Feb 21 09:17:58 CST 2017
     */
    private String val;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dic.dic_type
     *
     * @mbggenerated Tue Feb 21 09:17:58 CST 2017
     */
    private String dicType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dic.id
     *
     * @return the value of sys_dic.id
     *
     * @mbggenerated Tue Feb 21 09:17:58 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dic.id
     *
     * @param id the value for sys_dic.id
     *
     * @mbggenerated Tue Feb 21 09:17:58 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dic.name
     *
     * @return the value of sys_dic.name
     *
     * @mbggenerated Tue Feb 21 09:17:58 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dic.name
     *
     * @param name the value for sys_dic.name
     *
     * @mbggenerated Tue Feb 21 09:17:58 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dic.val
     *
     * @return the value of sys_dic.val
     *
     * @mbggenerated Tue Feb 21 09:17:58 CST 2017
     */
    public String getVal() {
        return val;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dic.val
     *
     * @param val the value for sys_dic.val
     *
     * @mbggenerated Tue Feb 21 09:17:58 CST 2017
     */
    public void setVal(String val) {
        this.val = val;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dic.dic_type
     *
     * @return the value of sys_dic.dic_type
     *
     * @mbggenerated Tue Feb 21 09:17:58 CST 2017
     */
    public String getDicType() {
        return dicType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dic.dic_type
     *
     * @param dicType the value for sys_dic.dic_type
     *
     * @mbggenerated Tue Feb 21 09:17:58 CST 2017
     */
    public void setDicType(String dicType) {
        this.dicType = dicType;
    }
}