package com.app.market.dao.entity.sys.mybatis;

public class SysOrg {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.id
     *
     * @mbggenerated Wed Mar 01 09:26:09 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.name
     *
     * @mbggenerated Wed Mar 01 09:26:09 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.flag
     *
     * @mbggenerated Wed Mar 01 09:26:09 CST 2017
     */
    private String flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.address
     *
     * @mbggenerated Wed Mar 01 09:26:09 CST 2017
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.contact
     *
     * @mbggenerated Wed Mar 01 09:26:09 CST 2017
     */
    private String contact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.mobile
     *
     * @mbggenerated Wed Mar 01 09:26:09 CST 2017
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.status
     *
     * @mbggenerated Wed Mar 01 09:26:09 CST 2017
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.id
     *
     * @return the value of sys_org.id
     *
     * @mbggenerated Wed Mar 01 09:26:09 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.id
     *
     * @param id the value for sys_org.id
     *
     * @mbggenerated Wed Mar 01 09:26:09 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.name
     *
     * @return the value of sys_org.name
     *
     * @mbggenerated Wed Mar 01 09:26:09 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.name
     *
     * @param name the value for sys_org.name
     *
     * @mbggenerated Wed Mar 01 09:26:09 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.flag
     *
     * @return the value of sys_org.flag
     *
     * @mbggenerated Wed Mar 01 09:26:09 CST 2017
     */
    public String getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.flag
     *
     * @param flag the value for sys_org.flag
     *
     * @mbggenerated Wed Mar 01 09:26:09 CST 2017
     */
    public void setFlag(String flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.address
     *
     * @return the value of sys_org.address
     *
     * @mbggenerated Wed Mar 01 09:26:09 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.address
     *
     * @param address the value for sys_org.address
     *
     * @mbggenerated Wed Mar 01 09:26:09 CST 2017
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.contact
     *
     * @return the value of sys_org.contact
     *
     * @mbggenerated Wed Mar 01 09:26:09 CST 2017
     */
    public String getContact() {
        return contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.contact
     *
     * @param contact the value for sys_org.contact
     *
     * @mbggenerated Wed Mar 01 09:26:09 CST 2017
     */
    public void setContact(String contact) {
        this.contact = contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.mobile
     *
     * @return the value of sys_org.mobile
     *
     * @mbggenerated Wed Mar 01 09:26:09 CST 2017
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.mobile
     *
     * @param mobile the value for sys_org.mobile
     *
     * @mbggenerated Wed Mar 01 09:26:09 CST 2017
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.status
     *
     * @return the value of sys_org.status
     *
     * @mbggenerated Wed Mar 01 09:26:09 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.status
     *
     * @param status the value for sys_org.status
     *
     * @mbggenerated Wed Mar 01 09:26:09 CST 2017
     */
    public void setStatus(String status) {
        this.status = status;
    }
}