package com.app.market.dao.entity.sys.mybatis;

public class SysOrg {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.id
     *
     * @mbggenerated Tue Feb 21 17:01:45 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.name
     *
     * @mbggenerated Tue Feb 21 17:01:45 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.flag
     *
     * @mbggenerated Tue Feb 21 17:01:45 CST 2017
     */
    private String flag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.id
     *
     * @return the value of sys_org.id
     *
     * @mbggenerated Tue Feb 21 17:01:45 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.id
     *
     * @param id the value for sys_org.id
     *
     * @mbggenerated Tue Feb 21 17:01:45 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.name
     *
     * @return the value of sys_org.name
     *
     * @mbggenerated Tue Feb 21 17:01:45 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.name
     *
     * @param name the value for sys_org.name
     *
     * @mbggenerated Tue Feb 21 17:01:45 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.flag
     *
     * @return the value of sys_org.flag
     *
     * @mbggenerated Tue Feb 21 17:01:45 CST 2017
     */
    public String getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.flag
     *
     * @param flag the value for sys_org.flag
     *
     * @mbggenerated Tue Feb 21 17:01:45 CST 2017
     */
    public void setFlag(String flag) {
        this.flag = flag;
    }
}