package com.app.market.dao.entity.sys.mybatis;

public class SysOrgAuth {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org_auth.id
     *
     * @mbggenerated Wed Feb 22 10:21:25 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org_auth.org_id
     *
     * @mbggenerated Wed Feb 22 10:21:25 CST 2017
     */
    private String orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org_auth.auth_id
     *
     * @mbggenerated Wed Feb 22 10:21:25 CST 2017
     */
    private String authId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org_auth.id
     *
     * @return the value of sys_org_auth.id
     *
     * @mbggenerated Wed Feb 22 10:21:25 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org_auth.id
     *
     * @param id the value for sys_org_auth.id
     *
     * @mbggenerated Wed Feb 22 10:21:25 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org_auth.org_id
     *
     * @return the value of sys_org_auth.org_id
     *
     * @mbggenerated Wed Feb 22 10:21:25 CST 2017
     */
    public String getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org_auth.org_id
     *
     * @param orgId the value for sys_org_auth.org_id
     *
     * @mbggenerated Wed Feb 22 10:21:25 CST 2017
     */
    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org_auth.auth_id
     *
     * @return the value of sys_org_auth.auth_id
     *
     * @mbggenerated Wed Feb 22 10:21:25 CST 2017
     */
    public String getAuthId() {
        return authId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org_auth.auth_id
     *
     * @param authId the value for sys_org_auth.auth_id
     *
     * @mbggenerated Wed Feb 22 10:21:25 CST 2017
     */
    public void setAuthId(String authId) {
        this.authId = authId;
    }
}