package com.app.market.dao.entity.sys.mybatis;

import java.util.Date;

public class SysTimeList {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_time_list.bill_id
     *
     * @mbggenerated Tue Feb 28 11:18:06 CST 2017
     */
    private String billId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_time_list.create_user
     *
     * @mbggenerated Tue Feb 28 11:18:06 CST 2017
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_time_list.create_time
     *
     * @mbggenerated Tue Feb 28 11:18:06 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_time_list.update_user
     *
     * @mbggenerated Tue Feb 28 11:18:06 CST 2017
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_time_list.update_time
     *
     * @mbggenerated Tue Feb 28 11:18:06 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_time_list.bill_id
     *
     * @return the value of sys_time_list.bill_id
     *
     * @mbggenerated Tue Feb 28 11:18:06 CST 2017
     */
    public String getBillId() {
        return billId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_time_list.bill_id
     *
     * @param billId the value for sys_time_list.bill_id
     *
     * @mbggenerated Tue Feb 28 11:18:06 CST 2017
     */
    public void setBillId(String billId) {
        this.billId = billId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_time_list.create_user
     *
     * @return the value of sys_time_list.create_user
     *
     * @mbggenerated Tue Feb 28 11:18:06 CST 2017
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_time_list.create_user
     *
     * @param createUser the value for sys_time_list.create_user
     *
     * @mbggenerated Tue Feb 28 11:18:06 CST 2017
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_time_list.create_time
     *
     * @return the value of sys_time_list.create_time
     *
     * @mbggenerated Tue Feb 28 11:18:06 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_time_list.create_time
     *
     * @param createTime the value for sys_time_list.create_time
     *
     * @mbggenerated Tue Feb 28 11:18:06 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_time_list.update_user
     *
     * @return the value of sys_time_list.update_user
     *
     * @mbggenerated Tue Feb 28 11:18:06 CST 2017
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_time_list.update_user
     *
     * @param updateUser the value for sys_time_list.update_user
     *
     * @mbggenerated Tue Feb 28 11:18:06 CST 2017
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_time_list.update_time
     *
     * @return the value of sys_time_list.update_time
     *
     * @mbggenerated Tue Feb 28 11:18:06 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_time_list.update_time
     *
     * @param updateTime the value for sys_time_list.update_time
     *
     * @mbggenerated Tue Feb 28 11:18:06 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}