package com.app.market.dao.mapper.agent.mybatis;

import com.app.market.dao.entity.agent.mybatis.AgentPointsChangeDetail;
import com.app.market.dao.entity.agent.mybatis.AgentPointsChangeDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AgentPointsChangeDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_points_change_detail
     *
     * @mbggenerated Mon Mar 13 18:25:35 CST 2017
     */
    int countByExample(AgentPointsChangeDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_points_change_detail
     *
     * @mbggenerated Mon Mar 13 18:25:35 CST 2017
     */
    int deleteByExample(AgentPointsChangeDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_points_change_detail
     *
     * @mbggenerated Mon Mar 13 18:25:35 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_points_change_detail
     *
     * @mbggenerated Mon Mar 13 18:25:35 CST 2017
     */
    int insert(AgentPointsChangeDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_points_change_detail
     *
     * @mbggenerated Mon Mar 13 18:25:35 CST 2017
     */
    int insertSelective(AgentPointsChangeDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_points_change_detail
     *
     * @mbggenerated Mon Mar 13 18:25:35 CST 2017
     */
    List<AgentPointsChangeDetail> selectByExample(AgentPointsChangeDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_points_change_detail
     *
     * @mbggenerated Mon Mar 13 18:25:35 CST 2017
     */
    AgentPointsChangeDetail selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_points_change_detail
     *
     * @mbggenerated Mon Mar 13 18:25:35 CST 2017
     */
    int updateByExampleSelective(@Param("record") AgentPointsChangeDetail record, @Param("example") AgentPointsChangeDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_points_change_detail
     *
     * @mbggenerated Mon Mar 13 18:25:35 CST 2017
     */
    int updateByExample(@Param("record") AgentPointsChangeDetail record, @Param("example") AgentPointsChangeDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_points_change_detail
     *
     * @mbggenerated Mon Mar 13 18:25:35 CST 2017
     */
    int updateByPrimaryKeySelective(AgentPointsChangeDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_points_change_detail
     *
     * @mbggenerated Mon Mar 13 18:25:35 CST 2017
     */
    int updateByPrimaryKey(AgentPointsChangeDetail record);
}