package com.app.market.dao.entity.asset.mybatis;

public class AssetManage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_manage.id
     *
     * @mbggenerated Wed Mar 29 10:55:53 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_manage.asset_id
     *
     * @mbggenerated Wed Mar 29 10:55:53 CST 2017
     */
    private String assetId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_manage.user_id
     *
     * @mbggenerated Wed Mar 29 10:55:53 CST 2017
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_manage.qty
     *
     * @mbggenerated Wed Mar 29 10:55:53 CST 2017
     */
    private Integer qty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_manage.status
     *
     * @mbggenerated Wed Mar 29 10:55:53 CST 2017
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_manage.id
     *
     * @return the value of asset_manage.id
     *
     * @mbggenerated Wed Mar 29 10:55:53 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_manage.id
     *
     * @param id the value for asset_manage.id
     *
     * @mbggenerated Wed Mar 29 10:55:53 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_manage.asset_id
     *
     * @return the value of asset_manage.asset_id
     *
     * @mbggenerated Wed Mar 29 10:55:53 CST 2017
     */
    public String getAssetId() {
        return assetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_manage.asset_id
     *
     * @param assetId the value for asset_manage.asset_id
     *
     * @mbggenerated Wed Mar 29 10:55:53 CST 2017
     */
    public void setAssetId(String assetId) {
        this.assetId = assetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_manage.user_id
     *
     * @return the value of asset_manage.user_id
     *
     * @mbggenerated Wed Mar 29 10:55:53 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_manage.user_id
     *
     * @param userId the value for asset_manage.user_id
     *
     * @mbggenerated Wed Mar 29 10:55:53 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_manage.qty
     *
     * @return the value of asset_manage.qty
     *
     * @mbggenerated Wed Mar 29 10:55:53 CST 2017
     */
    public Integer getQty() {
        return qty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_manage.qty
     *
     * @param qty the value for asset_manage.qty
     *
     * @mbggenerated Wed Mar 29 10:55:53 CST 2017
     */
    public void setQty(Integer qty) {
        this.qty = qty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_manage.status
     *
     * @return the value of asset_manage.status
     *
     * @mbggenerated Wed Mar 29 10:55:53 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_manage.status
     *
     * @param status the value for asset_manage.status
     *
     * @mbggenerated Wed Mar 29 10:55:53 CST 2017
     */
    public void setStatus(String status) {
        this.status = status;
    }
}