package com.app.market.dao.entity.asset.mybatis;

public class AssetRegister {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_register.id
     *
     * @mbggenerated Mon Mar 27 09:36:45 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_register.asset_num
     *
     * @mbggenerated Mon Mar 27 09:36:45 CST 2017
     */
    private String assetNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_register.name
     *
     * @mbggenerated Mon Mar 27 09:36:45 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_register.remark
     *
     * @mbggenerated Mon Mar 27 09:36:45 CST 2017
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_register.status
     *
     * @mbggenerated Mon Mar 27 09:36:45 CST 2017
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_register.qty
     *
     * @mbggenerated Mon Mar 27 09:36:45 CST 2017
     */
    private Integer qty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_register.org_id
     *
     * @mbggenerated Mon Mar 27 09:36:45 CST 2017
     */
    private String orgId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_register.id
     *
     * @return the value of asset_register.id
     *
     * @mbggenerated Mon Mar 27 09:36:45 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_register.id
     *
     * @param id the value for asset_register.id
     *
     * @mbggenerated Mon Mar 27 09:36:45 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_register.asset_num
     *
     * @return the value of asset_register.asset_num
     *
     * @mbggenerated Mon Mar 27 09:36:45 CST 2017
     */
    public String getAssetNum() {
        return assetNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_register.asset_num
     *
     * @param assetNum the value for asset_register.asset_num
     *
     * @mbggenerated Mon Mar 27 09:36:45 CST 2017
     */
    public void setAssetNum(String assetNum) {
        this.assetNum = assetNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_register.name
     *
     * @return the value of asset_register.name
     *
     * @mbggenerated Mon Mar 27 09:36:45 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_register.name
     *
     * @param name the value for asset_register.name
     *
     * @mbggenerated Mon Mar 27 09:36:45 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_register.remark
     *
     * @return the value of asset_register.remark
     *
     * @mbggenerated Mon Mar 27 09:36:45 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_register.remark
     *
     * @param remark the value for asset_register.remark
     *
     * @mbggenerated Mon Mar 27 09:36:45 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_register.status
     *
     * @return the value of asset_register.status
     *
     * @mbggenerated Mon Mar 27 09:36:45 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_register.status
     *
     * @param status the value for asset_register.status
     *
     * @mbggenerated Mon Mar 27 09:36:45 CST 2017
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_register.qty
     *
     * @return the value of asset_register.qty
     *
     * @mbggenerated Mon Mar 27 09:36:45 CST 2017
     */
    public Integer getQty() {
        return qty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_register.qty
     *
     * @param qty the value for asset_register.qty
     *
     * @mbggenerated Mon Mar 27 09:36:45 CST 2017
     */
    public void setQty(Integer qty) {
        this.qty = qty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_register.org_id
     *
     * @return the value of asset_register.org_id
     *
     * @mbggenerated Mon Mar 27 09:36:45 CST 2017
     */
    public String getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_register.org_id
     *
     * @param orgId the value for asset_register.org_id
     *
     * @mbggenerated Mon Mar 27 09:36:45 CST 2017
     */
    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }
}