package com.app.market.dao.mapper.crm.mybatis;

import com.app.market.dao.entity.crm.mybatis.CrmSupInfo;
import com.app.market.dao.entity.crm.mybatis.CrmSupInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CrmSupInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_sup_info
     *
     * @mbggenerated Wed Mar 01 15:35:41 CST 2017
     */
    int countByExample(CrmSupInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_sup_info
     *
     * @mbggenerated Wed Mar 01 15:35:41 CST 2017
     */
    int deleteByExample(CrmSupInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_sup_info
     *
     * @mbggenerated Wed Mar 01 15:35:41 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_sup_info
     *
     * @mbggenerated Wed Mar 01 15:35:41 CST 2017
     */
    int insert(CrmSupInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_sup_info
     *
     * @mbggenerated Wed Mar 01 15:35:41 CST 2017
     */
    int insertSelective(CrmSupInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_sup_info
     *
     * @mbggenerated Wed Mar 01 15:35:41 CST 2017
     */
    List<CrmSupInfo> selectByExample(CrmSupInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_sup_info
     *
     * @mbggenerated Wed Mar 01 15:35:41 CST 2017
     */
    CrmSupInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_sup_info
     *
     * @mbggenerated Wed Mar 01 15:35:41 CST 2017
     */
    int updateByExampleSelective(@Param("record") CrmSupInfo record, @Param("example") CrmSupInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_sup_info
     *
     * @mbggenerated Wed Mar 01 15:35:41 CST 2017
     */
    int updateByExample(@Param("record") CrmSupInfo record, @Param("example") CrmSupInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_sup_info
     *
     * @mbggenerated Wed Mar 01 15:35:41 CST 2017
     */
    int updateByPrimaryKeySelective(CrmSupInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_sup_info
     *
     * @mbggenerated Wed Mar 01 15:35:41 CST 2017
     */
    int updateByPrimaryKey(CrmSupInfo record);
}