package com.app.market.dao.mapper.oa.mybatis;

import com.app.market.dao.entity.oa.mybatis.OaAttendance;
import com.app.market.dao.entity.oa.mybatis.OaAttendanceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OaAttendanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_attendance
     *
     * @mbggenerated Tue Mar 21 13:36:26 CST 2017
     */
    int countByExample(OaAttendanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_attendance
     *
     * @mbggenerated Tue Mar 21 13:36:26 CST 2017
     */
    int deleteByExample(OaAttendanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_attendance
     *
     * @mbggenerated Tue Mar 21 13:36:26 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_attendance
     *
     * @mbggenerated Tue Mar 21 13:36:26 CST 2017
     */
    int insert(OaAttendance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_attendance
     *
     * @mbggenerated Tue Mar 21 13:36:26 CST 2017
     */
    int insertSelective(OaAttendance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_attendance
     *
     * @mbggenerated Tue Mar 21 13:36:26 CST 2017
     */
    List<OaAttendance> selectByExample(OaAttendanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_attendance
     *
     * @mbggenerated Tue Mar 21 13:36:26 CST 2017
     */
    OaAttendance selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_attendance
     *
     * @mbggenerated Tue Mar 21 13:36:26 CST 2017
     */
    int updateByExampleSelective(@Param("record") OaAttendance record, @Param("example") OaAttendanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_attendance
     *
     * @mbggenerated Tue Mar 21 13:36:26 CST 2017
     */
    int updateByExample(@Param("record") OaAttendance record, @Param("example") OaAttendanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_attendance
     *
     * @mbggenerated Tue Mar 21 13:36:26 CST 2017
     */
    int updateByPrimaryKeySelective(OaAttendance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_attendance
     *
     * @mbggenerated Tue Mar 21 13:36:26 CST 2017
     */
    int updateByPrimaryKey(OaAttendance record);
}