package com.app.market.dao.mapper.oa.mybatis;

import com.app.market.dao.entity.oa.mybatis.OaNotice;
import com.app.market.dao.entity.oa.mybatis.OaNoticeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OaNoticeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_notice
     *
     * @mbggenerated Fri Mar 17 09:20:55 CST 2017
     */
    int countByExample(OaNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_notice
     *
     * @mbggenerated Fri Mar 17 09:20:55 CST 2017
     */
    int deleteByExample(OaNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_notice
     *
     * @mbggenerated Fri Mar 17 09:20:55 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_notice
     *
     * @mbggenerated Fri Mar 17 09:20:55 CST 2017
     */
    int insert(OaNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_notice
     *
     * @mbggenerated Fri Mar 17 09:20:55 CST 2017
     */
    int insertSelective(OaNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_notice
     *
     * @mbggenerated Fri Mar 17 09:20:55 CST 2017
     */
    List<OaNotice> selectByExample(OaNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_notice
     *
     * @mbggenerated Fri Mar 17 09:20:55 CST 2017
     */
    OaNotice selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_notice
     *
     * @mbggenerated Fri Mar 17 09:20:55 CST 2017
     */
    int updateByExampleSelective(@Param("record") OaNotice record, @Param("example") OaNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_notice
     *
     * @mbggenerated Fri Mar 17 09:20:55 CST 2017
     */
    int updateByExample(@Param("record") OaNotice record, @Param("example") OaNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_notice
     *
     * @mbggenerated Fri Mar 17 09:20:55 CST 2017
     */
    int updateByPrimaryKeySelective(OaNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_notice
     *
     * @mbggenerated Fri Mar 17 09:20:55 CST 2017
     */
    int updateByPrimaryKey(OaNotice record);
}